version: '3.7'

services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 6444:5432
    networks:
      - default
      - common-net


  app:
    build: .
    volumes:
      - ./src:/src:rw
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.app
    networks:
      - default
      - common-net
    environment:
      PROCESS: DEV_DJANGO



networks:
  default:
    driver: bridge
  common-net:
    external: true
